### ISSUE TITLE
Support SQL files 

### ISSUE THREAD

**Issue by hoegge** [Sysmagine/SemanticDiff#48] opened 2023-12-14 09:13 UTC
Would be great if there was support for SQL ... and specifically if it also could ignore repeated "GO" statements that does not have any function.

**Comment by mmueller2012** [comment] 2024-01-17 07:06
Thanks for your report. There is already an existing issue for SQL. Please subscribe to #12 to stay up-to-date.

**Comment by mmueller2012** [comment] 2024-01-17 07:07
Duplicate of #12

**Closed** 2024-01-17 07:07 UTC
Labels: enhancement
