### ISSUE TITLE
go & tsx files saying "This type of diff is not supported by SemanticDiff."

### ISSUE THREAD

**Issue by partounian** [Sysmagine/SemanticDiff#33] opened 2023-08-07 20:34 UTC
**Describe the Bug**
Hitting Cmd-Shift-P to search enable/switch to SemanticDiff in my go or tsx files through the error "This type of diff is not supported by SemanticDiff." (currently trying to resolve a merge conflict in my git repo)

**To Reproduce**
1. Have a merge conflict in progress
2. Open a .go or .tsx file.
3. Hit Cmd-Shift-P and search for Semantic Diff.
4. Choose option "Switch to SemanticDiff"
5. See error

**Expected Behavior**

**Actual Behavior**

**Screenshots**

**Source Code**

**SemanticDiff Version**
v0.8.4

**VS Code Information**
```
Version: 1.81.0
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:38:28.722Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0
```

**Additional Context**

**Comment by slackner** [comment] 2023-08-09 07:18
Thanks for reporting this issue.

The problem is not the lack of go or tsx support, but the limitation that SemanticDiff is only available when a diff view has already been opened in VS Code.

If you want to compare the current and incoming changes, you can do that by clicking "Compare Changes" (see screenshot). Afterwards, you can open SemanticDiff by clicking on the button in the top navigation bar or pressing Cmd-Shift-P and selecting "Switch to SemanticDiff".

![image](https://github.com/Sysmagine/SemanticDiff/assets/5781160/1d8b1ca4-d5ba-4948-a1ec-e00190bba6ca)

Note that there is currently no support for resolving merge conflicts directly within SemanticDiff. In its current version, it is mainly for viewing diffs. So you would have to take the information and then go back to the editor to do the actual changes. We're aware that this is less than ideal and might add support for merge conflict resolution tools in a future version.

**Closed** 2023-08-09 18:31 UTC
Labels: bug
